export const GET_USERS_ACTION = 'GET_USERS_ACTION';
export const GET_USERS_SUCCESSED_ACTION = 'GET_USERS_SUCCESSED_ACTION';
export const GET_USERS_FAILED_ACTION = 'GET_USERS_FAILED_ACTION';

export const GET_USER_ACTION = 'GET_USER_ACTION';
export const GET_USER_SUCCESSED_ACTION = 'GET_USER_SUCCESSED_ACTION';
export const GET_USER_FAILED_ACTION = 'GET_USER_FAILED_ACTION';

export const CREATE_USER_ACTION = 'CREATE_USER_ACTION';
export const CREATE_USER_SUCCESSED_ACTION = 'CREATE_USER_SUCCESSED_ACTION';
export const CREATE_USER_FAILED_ACTION = 'CREATE_USER_FAILED_ACTION';

export const UPDATE_USER_ACTION = 'UPDATE_USER_ACTION';
export const UPDATE_USER_SUCCESSED_ACTION = 'UPDATE_USER_SUCCESSED_ACTION';
export const UPDATE_USER_FAILED_ACTION = 'UPDATE_USER_FAILED_ACTION';

export const DELETE_USER_ACTION = 'DELETE_USER_ACTION';
export const DELETE_USER_SUCCESSED_ACTION = 'DELETE_USER_SUCCESSED_ACTION';
export const DELETE_USER_FAILED_ACTION = 'DELETE_USER_FAILED_ACTION';
