export const GET_COMMENTS_ACTION = 'GET_COMMENTS_ACTION';
export const GET_COMMENTS_SUCCESSED_ACTION = 'GET_COMMENTS_SUCCESSED_ACTION';
export const GET_COMMENTS_FAILED_ACTION = 'GET_COMMENTS_FAILED_ACTION';

export const GET_COMMENT_ACTION = 'GET_COMMENT_ACTION';
export const GET_COMMENT_SUCCESSED_ACTION = 'GET_COMMENT_SUCCESSED_ACTION';
export const GET_COMMENT_FAILED_ACTION = 'GET_COMMENT_FAILED_ACTION';

export const CREATE_COMMENT_ACTION = 'CREATE_COMMENT_ACTION';
export const CREATE_COMMENT_SUCCESSED_ACTION = 'CREATE_COMMENT_SUCCESSED_ACTION';
export const CREATE_COMMENT_FAILED_ACTION = 'CREATE_COMMENT_FAILED_ACTION';

export const UPDATE_COMMENT_ACTION = 'UPDATE_COMMENT_ACTION';
export const UPDATE_COMMENT_SUCCESSED_ACTION = 'UPDATE_COMMENT_SUCCESSED_ACTION';
export const UPDATE_COMMENT_FAILED_ACTION = 'UPDATE_COMMENT_FAILED_ACTION';

export const DELETE_COMMENT_ACTION = 'DELETE_COMMENT_ACTION';
export const DELETE_COMMENT_SUCCESSED_ACTION = 'DELETE_COMMENT_SUCCESSED_ACTION';
export const DELETE_COMMENT_FAILED_ACTION = 'DELETE_COMMENT_FAILED_ACTION';
